### PR TITLE
docs: Add `.gitignore`

### PR DESCRIPTION
**Pull request by karfau**
To avoid certain files accidentally being committed.

Rewrote the README.md since this is a public repo.

### CODE REVIEW

**Comment by karfau** [comment]
To add some context: 

Recently somebody contributed to one of our projects and committed his IDE configuration to the repo.

I still believe people using an IDE should have the related ignores configured on their machine, but the more people work on a project the more cumbersome and error prone this perspective becomes.

So I was thinking about the bigger picture and came up with this solution, which will streamline the process of spreading consistency.

**Review by AnBauer — APPROVED** [review]
This is a great idea! ❤️

**Comment by cakemanny** [comment]
I like the thought! (And I also agree with "people using an IDE should have the related ignores configured on their machine")

I'm not really sure I understand the mechanism....
I did follow the [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#about-default-community-health-files) ..

So, it's a `.gitignore` file for projects that don't have one...
  and also a recommended one, that can be synced into the projects
    except that its contents ought not to go into the projects, when I read [this comment](https://github.com/bettermarks/.github/pull/1/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R6) and understood it properly
    
To me it's unclear which way was decided.
_But I often find I've misread something only after I reply... :)_

PS: Am I right in thinking some of the rules came from https://github.com/github/gitignore/tree/main/Global ?

**Comment by karfau** [comment]
@cakemanny 
> PS: Am I right in thinking some of the rules came from [github/gitignore@main/Global](https://github.com/github/gitignore/tree/main/Global?rgh-link-date=2023-12-06T12%3A48%3A45Z) ?

yes I took some inspiration from the ones provided by GitHub (and my IDE), but I tweaked them to be a bit more narrow in scope, related to what we do.

You are right, the comment in the gitignore file is at least confusing (you don't have to, but you can use it this way).
(Once the branch lands) the link on the top of the file leads to [the section in the updated readme explaining how to use it](https://github.com/bettermarks/.github/blob/add-gitignore/README.md#gitignore)

I don't explicitly mention where you can or should copy the file to, because I thought it's obvious... but maybe that is the missing point?

let me know.

**Review by ffauchille — APPROVED** [review]

**Pull request merged**
